// Auto-generated by: npx supabase gen types typescript --local > lib/supabase/types.ts
// Do not edit manually — regenerate after every migration.
//
// STRUCTURAL NOTES — do not remove these comments when regenerating:
//
// 1. Json uses lazy interfaces instead of a recursive type alias.
//    Recursive type aliases are eagerly expanded. When PersonRow (which has
//    sources: Json, titles: Json) flows through tRPC v11's conditional type
//    layers (inferProcedureOutput → DeepPartial → TRPCRequestOptions) TypeScript
//    hits the instantiation depth limit → TS2589. Interface bodies are evaluated
//    lazily, breaking the chain.
//
// 2. PersonsRow is defined outside Database so Functions['search_persons']['Returns']
//    can reference it without a self-referential cycle inside the Database literal.
//
// 3. Every Table must include Relationships: GenericRelationship[].
//    supabase-js v2.100+ requires Database['public'] to satisfy GenericSchema:
//      { Tables: Record<string, GenericTable>; Views: Record<string, GenericView>; Functions: Record<string, GenericFunction> }
//    GenericTable = { Row; Insert; Update; Relationships: GenericRelationship[] }
//    Missing Relationships → table doesn't extend GenericTable → Tables doesn't
//    extend Record<string, GenericTable> → Database['public'] doesn't extend
//    GenericSchema → Schema = never inside SupabaseClient generics → rpc() Args
//    constraint resolves to never → args?: undefined → TS2345.
//
// 4. Views: {} must be present for the same GenericSchema conformance reason.
//
// 5. Functions['search_persons']['Returns'] uses unknown for the Json columns
//    (sources, titles). GetRpcFunctionFilterBuilderByArgs evaluates the Returns
//    type during rpc() overload resolution. Json in Returns would re-trigger
//    the instantiation depth explosion that Relationships and lazy Json normally
//    prevent at the tRPC layer.

// Lazy-interface Json — structurally identical to the recursive type alias but
// evaluated lazily. Prevents TS2589 when Json flows through tRPC/supabase-js
// deep conditional type chains.
export interface JsonObject { [key: string]: Json | undefined }
export interface JsonArray extends Array<Json> {}
export type Json = string | number | boolean | null | JsonObject | JsonArray

// PersonsRow lifted out of Database — see note 2 above.
export type PersonsRow = {
  id: string
  name_ar: string
  name_en: string
  father_id: string | null
  branch: 'hasanid' | 'husaynid' | 'hashemite' | null
  scholarly_tradition: 'sunni' | 'shia' | 'both' | null
  generation: number | null
  birth_date_hijri: string | null
  death_date_hijri: string | null
  birth_date_gregorian: string | null
  death_date_gregorian: string | null
  bio_ar: string | null
  bio_en: string | null
  sources: Json
  titles: Json
  is_verified: boolean
  is_living: boolean
  // Feature 1 columns — added by migration 20260401000000
  gender: 'male' | 'female' | 'unknown'
  mother_id: string | null
  marriage_id: string | null
  photo_url: string | null
  created_at: string
  updated_at: string
}

// MarriagesRow — added by migration 20260401000000
export type MarriagesRow = {
  id: string
  husband_id: string
  wife_id: string
  date_hijri: string | null
  date_gregorian: string | null
  order_num: number
  is_verified: boolean
  notes_ar: string | null
  notes_en: string | null
  created_at: string
  updated_at: string
}

export type Database = {
  public: {
    Tables: {
      marriages: {
        Row: MarriagesRow
        Insert: Omit<MarriagesRow, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<MarriagesRow, 'id' | 'created_at' | 'updated_at'>>
        Relationships: [
          {
            foreignKeyName: 'marriages_husband_id_fkey'
            columns: ['husband_id']
            isOneToOne: false
            referencedRelation: 'persons'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'marriages_wife_id_fkey'
            columns: ['wife_id']
            isOneToOne: false
            referencedRelation: 'persons'
            referencedColumns: ['id']
          }
        ]
      }
      persons: {
        Row: PersonsRow
        Insert: Omit<PersonsRow, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<PersonsRow, 'id' | 'created_at' | 'updated_at'>>
        Relationships: [
          {
            foreignKeyName: 'persons_father_id_fkey'
            columns: ['father_id']
            isOneToOne: false
            referencedRelation: 'persons'
            referencedColumns: ['id']
          }
        ]
      }
      submissions: {
        Row: {
          id: string
          user_id: string
          claimed_father_id: string | null
          full_name_ar: string
          full_name_en: string
          proof_documents: Json
          status: 'pending' | 'under_review' | 'approved' | 'rejected'
          verifier_id: string | null
          verifier_notes: string | null
          rejection_reason: string | null
          submitted_at: string
          reviewed_at: string | null
          can_resubmit_after: string | null
        }
        Insert: Omit<Database['public']['Tables']['submissions']['Row'], 'id' | 'submitted_at'>
        Update: Partial<Database['public']['Tables']['submissions']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'submissions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'submissions_claimed_father_id_fkey'
            columns: ['claimed_father_id']
            isOneToOne: false
            referencedRelation: 'persons'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'submissions_verifier_id_fkey'
            columns: ['verifier_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      users: {
        Row: {
          id: string
          display_name: string | null
          role: 'user' | 'verifier' | 'admin' | 'superadmin'
          preferred_locale: 'ar' | 'en'
          linked_person_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'users_linked_person_id_fkey'
            columns: ['linked_person_id']
            isOneToOne: false
            referencedRelation: 'persons'
            referencedColumns: ['id']
          }
        ]
      }
      audit_log: {
        Row: {
          id: string
          table_name: string
          record_id: string
          action: 'INSERT' | 'UPDATE' | 'DELETE'
          changed_by: string | null
          old_data: Json | null
          new_data: Json | null
          ip_address: string | null
          changed_at: string
        }
        Insert: Omit<Database['public']['Tables']['audit_log']['Row'], 'id' | 'changed_at'>
        Update: never
        Relationships: [
          {
            foreignKeyName: 'audit_log_changed_by_fkey'
            columns: ['changed_by']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
    }
    // Views must be present for Database['public'] to satisfy GenericSchema.
    Views: {}
    Functions: {
      search_persons: {
        Args: {
          query: string
          branch_filter?: string | null
          result_limit?: number
        }
        // Returns uses unknown for Json columns — see note 5 above.
        Returns: {
          id: string
          name_ar: string
          name_en: string
          father_id: string | null
          branch: 'hasanid' | 'husaynid' | 'hashemite' | null
          scholarly_tradition: 'sunni' | 'shia' | 'both' | null
          generation: number | null
          birth_date_hijri: string | null
          death_date_hijri: string | null
          birth_date_gregorian: string | null
          death_date_gregorian: string | null
          bio_ar: string | null
          bio_en: string | null
          sources: unknown
          titles: unknown
          is_verified: boolean
          is_living: boolean
          created_at: string
          updated_at: string
        }[]
      }
    }
  }
}
