// Auto-generated by: npx supabase gen types typescript --local > lib/supabase/types.ts
// Do not edit manually — regenerate after every migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      persons: {
        Row: {
          id: string
          name_ar: string
          name_en: string
          father_id: string | null
          branch: 'hasanid' | 'husaynid' | 'hashemite' | null
          scholarly_tradition: 'sunni' | 'shia' | 'both' | null
          generation: number | null
          birth_date_hijri: string | null
          death_date_hijri: string | null
          birth_date_gregorian: string | null
          death_date_gregorian: string | null
          bio_ar: string | null
          bio_en: string | null
          sources: Json
          titles: Json
          is_verified: boolean
          is_living: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['persons']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['persons']['Insert']>
      }
      submissions: {
        Row: {
          id: string
          user_id: string
          claimed_father_id: string | null
          full_name_ar: string
          full_name_en: string
          proof_documents: Json
          status: 'pending' | 'under_review' | 'approved' | 'rejected'
          verifier_id: string | null
          verifier_notes: string | null
          rejection_reason: string | null
          submitted_at: string
          reviewed_at: string | null
          can_resubmit_after: string | null
        }
        Insert: Omit<Database['public']['Tables']['submissions']['Row'], 'id' | 'submitted_at'>
        Update: Partial<Database['public']['Tables']['submissions']['Insert']>
      }
      users: {
        Row: {
          id: string
          display_name: string | null
          role: 'user' | 'verifier' | 'admin' | 'superadmin'
          preferred_locale: 'ar' | 'en'
          linked_person_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      audit_log: {
        Row: {
          id: string
          table_name: string
          record_id: string
          action: 'INSERT' | 'UPDATE' | 'DELETE'
          changed_by: string | null
          old_data: Json | null
          new_data: Json | null
          ip_address: string | null
          changed_at: string
        }
        Insert: Omit<Database['public']['Tables']['audit_log']['Row'], 'id' | 'changed_at'>
        Update: never
      }
    }
    Functions: {
      search_persons: {
        Args: {
          query: string
          branch_filter?: string | null
          result_limit?: number
        }
        Returns: Database['public']['Tables']['persons']['Row'][]
      }
    }
  }
}
